name: Documentation updater

on:
  push:
    paths:
      - "docs/**/*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:           
      contents: write           # 'write' access to repository contents
      
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
                
    - name: Generate documentation
      run: |
        python docs/scripts/generator.py
                
    - name: Commit and push
      run: |
        git config --local user.email "doc-generator[bot]@users.noreply.github.com"
        git config --local user.name "doc-generator[bot]"
        git commit -a -m "Auto-update documentation"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}